### ISSUE TITLE
Vercel Deployment

### ISSUE THREAD

**Issue by ProxyEmpireIsTaken** [dragon731012/DM-unbl0cker-bare-server#1]
I was wondering if this could be deployed to vercel. If so how?

**Comment by dragon731012** [comment]
I'll look into that

**Comment by dragon731012** [comment]
added, thanks to sauc23's version of the bare server. (https://github.com/sauc23/Vercel-Bare-Server/)

**Comment by dragon731012** [comment]
deploy with this link: https://vercel.com/new/clone?repositoryurl=https://github.com/dragon731012/DM-unbl0cker-bare-server

**Comment by ProxyEmpireIsTaken** [comment]
thanks!

**Comment by dragon731012** [comment]
no problem
